### ISSUE TITLE
Re-fork repositories to avoid confusion

### ISSUE THREAD

**Issue by jcfr** [NIRALUser/MeshToLabelMap#5]
@fbudin69500  To avoid confusion, could you delete your project `fbudin69500/MeshToLabelMap` and re-fork the one hosted in the `DCBIA-OrthoLab` organization. See https://github.com/DCBIA-OrthoLab/MeshToLabelMap

The fork currently shows this:

![image](https://user-images.githubusercontent.com/219043/70097867-693e8880-15f8-11ea-893f-94f914d16fbc.png)

Thanks :pray:

**Comment by jcfr** [comment]
Ping

**Comment by jcfr** [comment]
Ping

**Comment by fbudin69500** [comment]
I archived it in my repo. Is this enough?

**Comment by jcfr** [comment]
Thanks for the update, archiving is not enough.

As you can see, your repo still show as the root:

![image](https://user-images.githubusercontent.com/219043/78941350-80e5bc00-7a85-11ea-8335-c676e9e978b7.png)

**Comment by fbudin69500** [comment]
Done.

**Comment by jcfr** [comment]
Thanks :pray:
