### ISSUE TITLE
Module runs but output cannot be saved 

### ISSUE THREAD

**Issue by bpaniagua** [NIRALUser/MeshToLabelMap#7]
Slicer version: 4.11.0-2019-12-02 r28659
OS: Ubuntu 16.04

Error message
```
cannot write ImageData, it's NULL
```

**Comment by juanprietob** [comment]
Could you share the input data you are using?

**Comment by bpaniagua** [comment]
Yikes, I do not even remember what the problem was here. Closing for now.
